targets:
  $default:
    builders:
      flutter_tools|web_dev_server:
        options:
          headers:
            Cross-Origin-Opener-Policy: "same-origin"
            Cross-Origin-Embedder-Policy: "require-corp"